### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-moisson#1]
⚠️ Pas de rapport, pas tout le code... Si je vous propose deux itérations c'est pour votre bien...

**Comment by matthieuMoisson** [comment]
@Slashgear 
C'est ma faute je pensais que j'avais jusqu'au prochain TP. J’espère donc que ma seul chance ne sera pas mauvaise.
Cordialement

**Comment by matthieuMoisson** [comment]
@Slashgear 
Je ne pensais pas avoir fait quelque chose de si parfait. Pourtant aucune correction à signaler?

**Comment by Slashgear** [comment]
Pas de deuxième tour pour toi malheureusement.

**Comment by matthieuMoisson** [comment]
Pourquoi une troisième fois? Vous ne m'avez pas fait de second retour?

**Comment by matthieuMoisson** [comment]
@Slashgear 
Pourquoi une troisième fois? Vous ne m'avez pas fait de second retour?

**Comment by matthieuMoisson** [comment]
@Slashgear 
J'ai réalisé le tp jeudi de la semaine dernière (avec un jour de retard) et depuis vous ne m'avez rien dit.

**Comment by Slashgear** [comment]
(pas besoin mettre mon @ , je suis notifié dans tous les cas)

Mercredi soir j'ai relu ton TP. Je n'ai pas rédiger de remarques, car je ne comptais pas relire une nouvelle fois ton TP. Tu admettra que j'ai quand même passé du temps en fin de première semaine à lire un TP pas fini car tu n'avais rien rendu (car TU avais oublié)

Je vais t'écrire mes remarques ici : 

⚠️ Pourquoi faire des `System.out.printf("" + multiplication.toString());` avec des concaténation des String ?

⚠️ Il y a surement un moyen de ne pas utiliser la variable de retour et de passer par des paramètres. Plutôt que d'ajouter un deuxième `accept`dans tes entitées ? Si on a mis le patterne visitor en place c'est justement pour minimiser l'impact sur les entitées que l'on visite.

**Comment by matthieuMoisson** [comment]
L'habitude de mettre le @ excusez moi.

Je sais que vous passez du temps à relire les TP et je vous en remercie. (Tous les enseignants ne passent pas autant de temps à le faire).

Par contre je ne comprend pas car je n'ai pas vu les remarques que vous mentionnez si dessus. Ou apparaissent ces remarques?

Je sais également que vous ne pouvez relire mes TP trois fois et suis conscient que les modifications que j'apporterai seront pour moi source d'apprentissage.

Erreurs concaténation de String je n'avais pas vu c'est très moche.
Pour utiliser des variables, c'est ce que je voulais faire au début (j'y ai un peut réfléchi). Mais j'ai trouvé bien plus facile et rapide à implémenter ma méthode. Par contre comme vous dites je n'ai pas vraiment respecté le paterne visitor.

Cordialement
